# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-01-05 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建用户')),
                ('write_user', models.CharField(blank=True, max_length=64, null=True, verbose_name='更新用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('write_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='表名')),
                ('alias', models.CharField(blank=True, max_length=32, null=True, verbose_name='表别名')),
                ('prefix', models.CharField(blank=True, max_length=32, null=True, verbose_name='表名前缀')),
            ],
            options={
                'verbose_name': '模版-虚拟表',
                'db_table': 'cti',
            },
        ),
        migrations.CreateModel(
            name='TemplateAttribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建用户')),
                ('write_user', models.CharField(blank=True, max_length=64, null=True, verbose_name='更新用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('write_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='字段名')),
                ('alias', models.CharField(blank=True, max_length=32, null=True, verbose_name='字段别名')),
                ('type', models.CharField(max_length=32, verbose_name='字段类型')),
                ('readonly', models.BooleanField(default=False, verbose_name='只读')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
                ('unique', models.BooleanField(default=False, verbose_name='唯一')),
                ('sortable', models.BooleanField(default=True, verbose_name='排序')),
                ('priority', models.IntegerField(default=100, verbose_name='优先级')),
                ('filters', models.CharField(blank=True, max_length=256, null=True, verbose_name='过滤器')),
                ('default', models.CharField(blank=True, max_length=64, null=True, verbose_name='默认值')),
                ('s_cti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.CTI', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '模板属性',
                'db_table': 'template_attribution',
            },
        ),
        migrations.CreateModel(
            name='TemplateRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建用户')),
                ('write_user', models.CharField(blank=True, max_length=64, null=True, verbose_name='更新用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('write_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('alias', models.CharField(max_length=32, verbose_name='别名')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='关联类型')),
                ('s_cti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.CTI', verbose_name='源分类')),
                ('t_cti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.CTI', verbose_name='目标分类')),
                ('write_back_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.TemplateAttribution', verbose_name='回写字段')),
                ('write_back_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.CTI', verbose_name='回写模板')),
            ],
            options={
                'verbose_name': '模板关系',
                'db_table': 'template_relation',
            },
        ),
    ]
